name: atlive
description: A system
# version: 1.0.0
# homepage: https://redsolver.net
# author: redsolver <info@redsolver.net>

environment:
  sdk: '>=2.0.0-dev.63.0 <2.0.0'

dependencies:
  angular: ^5.0.0-beta
  angular_components: ^0.9.0-beta

  firebase: '^4.4.0'
  angular_forms: ^2.0.0-beta
  angular_router: ^2.0.0-alpha+15
  dbcrypt: any
  uuid: "^1.0.0"
  cookie: "^0.0.4"
  dnd: "^1.2.0"

  #http: ^0.11.0
  #stream_transform: ^0.0.6
  #pwa: "^0.1.10"
  #feedparser: "^0.0.2"
  #service_worker: "^0.2.1"

dev_dependencies:
  angular_test: ^2.0.0-beta
  build_runner: ^0.9.1
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
